# Common Errors

### Update Variables

`append`
* The Wrong Way

In [36]:
animals = ['dog', 'cat', 'panda']
more_animals = animals.append('giraffe')
print(more_animals)

None


* The Right Way

In [3]:
animals = ['dog', 'cat', 'panda']
animals.append('giraffe')
print(animals)

['dog', 'cat', 'panda', 'giraffe']


`sort`
* The Wrong Way

In [7]:
seq = [1, 5, 4, 2, 3]
sorted_seq = seq.sort()
print(sorted_seq)


None


* The Right Way

In [8]:
seq = [1, 5, 4, 2, 3]
seq.sort()
print(seq)

[1, 2, 3, 4, 5]


or

In [9]:
seq = [1, 5, 4, 2, 3]
sorted_seq = sorted(seq)
print(sorted_seq)

[1, 2, 3, 4, 5]


### Python List Methods vs. Numy Array Methods

* Multiplication `*`

In [57]:
list_ = [1, 3, 4] 
new_list = list_ * 3
print(new_list)

[1, 3, 4, 1, 3, 4, 1, 3, 4]


In [58]:
import numpy as np
arr = np.array(list_) 
new_arr = arr * 3
print(new_arr)

[ 3  9 12]


* Concatenation/Add `+`

In [13]:
list1, list2 = [1, 2, 3], [4, 5, 7]
new_list = list1 + list2
print(new_list)

[1, 2, 3, 4, 5, 7]


In [14]:
arr1, arr2 = np.array(list1), np.array(list2)
new_arr = arr1 + arr2
print(new_arr)

[ 5  7 10]


- COPY 

    - `copy.copy`      (shallow copy)
    - `numpy.copy`     (deep copy) 
    - `copy.deepcopy`
    - `numpy.view`


In [54]:

import copy

old_list = [[1,2,3], [4,5,6]]
new_list = old_list.copy()
# new_list = copy.copy(old_list)
old_list[0][0] = 100

print('old_list:\n', old_list)
print('\nnew_list:\n', new_list)


old_list:
 [[100, 2, 3], [4, 5, 6]]

new_list:
 [[100, 2, 3], [4, 5, 6]]


In [51]:
# numpy.copy
import numpy as np

old_arr = numpy.array([[1,2,3], [4,5,6]])
new_arr = old_arr.copy()
# new_arr = np.copy(old_arr)
old_arr[0][0] = 100

print('old_arr:\n', old_arr)
print('\nnew_arr:\n', new_arr)

old_arr:
 [[100   2   3]
 [  4   5   6]]

new_arr:
 [[1 2 3]
 [4 5 6]]


In [52]:
# copy.deepcopy

old_list = [[1,2,3], [4,5,6]]
new_list = copy.deepcopy(old_list)
old_list[0][0] = 100

print('old_list:\n', old_list)
print('\nnew_list:\n', new_list)

old_list:
 [[100, 2, 3], [4, 5, 6]]

new_list:
 [[1, 2, 3], [4, 5, 6]]


In [61]:
# numpy.view

old_arr = numpy.array([[1,2,3], [4,5,6]])
new_arr = old_arr.view().reshape(3,2)
old_arr[0][0] = 100

print('old_arr:\n', old_arr)
print('\nnew_arr:\n', new_arr)

old_arr:
 [[100   2   3]
 [  4   5   6]]

new_arr:
 [[100   2]
 [  3   4]
 [  5   6]]


### Iteration

In [76]:
list1 = ['apple']
tuple1 = ('apple')
tuple2 = ('apple',)

print('list1:')
for item in list1:
    print(item)

print('\ntuple1:')
for item in tuple1:
    print(item)

print('\ntuple2:')
for item in tuple2:
    print(item)


list1:
apple

tuple1:
a
p
p
l
e

tuple2:
apple


In [77]:
animals = ['cat', 'dog', 'panda']

print('indexing:')
for animal in animals[0]:
    print(animal)

print('\nslicing:')
for animal in animals[:1]:
    print(animal)


indexing:
c
a
t

slicing:
cat
